spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
spark.sql.catalog.rest=org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.rest.type=rest
spark.sql.catalog.rest.uri=http://iceberg-rest:8181
spark.sql.catalog.rest.warehouse=file:///tmp/iceberg-warehouse
spark.sql.catalog.rest.io-impl=org.apache.iceberg.hadoop.HadoopFileIO
spark.sql.defaultCatalog=rest
